//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCatalog.Services.BookService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookService.IBookService")]
    public interface IBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBooksCount", ReplyAction="http://tempuri.org/IBookService/GetBooksCountResponse")]
        int GetBooksCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBooksCount", ReplyAction="http://tempuri.org/IBookService/GetBooksCountResponse")]
        System.Threading.Tasks.Task<int> GetBooksCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel> GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAllBooks", ReplyAction="http://tempuri.org/IBookService/GetAllBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel>> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBooks", ReplyAction="http://tempuri.org/IBookService/GetBooksResponse")]
        BookCatalog.Services.BookService.GetBooksResponse GetBooks(BookCatalog.Services.BookService.GetBooksRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBooks", ReplyAction="http://tempuri.org/IBookService/GetBooksResponse")]
        System.Threading.Tasks.Task<BookCatalog.Services.BookService.GetBooksResponse> GetBooksAsync(BookCatalog.Services.BookService.GetBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/BookExists", ReplyAction="http://tempuri.org/IBookService/BookExistsResponse")]
        bool BookExists(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/BookExists", ReplyAction="http://tempuri.org/IBookService/BookExistsResponse")]
        System.Threading.Tasks.Task<bool> BookExistsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBook", ReplyAction="http://tempuri.org/IBookService/GetBookResponse")]
        BookCatalog.Components.ViewModels.BookViewModel GetBook(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetBook", ReplyAction="http://tempuri.org/IBookService/GetBookResponse")]
        System.Threading.Tasks.Task<BookCatalog.Components.ViewModels.BookViewModel> GetBookAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Manage", ReplyAction="http://tempuri.org/IBookService/ManageResponse")]
        int Manage(BookCatalog.Components.ViewModels.BookViewModel bookVM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Manage", ReplyAction="http://tempuri.org/IBookService/ManageResponse")]
        System.Threading.Tasks.Task<int> ManageAsync(BookCatalog.Components.ViewModels.BookViewModel bookVM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Delete", ReplyAction="http://tempuri.org/IBookService/DeleteResponse")]
        void Delete(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/Delete", ReplyAction="http://tempuri.org/IBookService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAuthors", ReplyAction="http://tempuri.org/IBookService/GetAuthorsResponse")]
        string GetAuthors(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetAuthors", ReplyAction="http://tempuri.org/IBookService/GetAuthorsResponse")]
        System.Threading.Tasks.Task<string> GetAuthorsAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/PopulateMultiSelectList", ReplyAction="http://tempuri.org/IBookService/PopulateMultiSelectListResponse")]
        System.Collections.Generic.List<System.Web.Mvc.SelectListItem> PopulateMultiSelectList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/PopulateMultiSelectList", ReplyAction="http://tempuri.org/IBookService/PopulateMultiSelectListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Web.Mvc.SelectListItem>> PopulateMultiSelectListAsync();
        
        // CODEGEN: Generating message contract since element name GetXMLResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetXML", ReplyAction="http://tempuri.org/IBookService/GetXMLResponse")]
        BookCatalog.Services.BookService.GetXMLResponse GetXML(BookCatalog.Services.BookService.GetXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService/GetXML", ReplyAction="http://tempuri.org/IBookService/GetXMLResponse")]
        System.Threading.Tasks.Task<BookCatalog.Services.BookService.GetXMLResponse> GetXMLAsync(BookCatalog.Services.BookService.GetXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooks", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.Dictionary<string, System.ComponentModel.ListSortDirection> sorts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Collections.Generic.List<BookCatalog.Infrastructure.Filtration.CustomFilter> filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int take;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int skip;
        
        public GetBooksRequest() {
        }
        
        public GetBooksRequest(System.Collections.Generic.Dictionary<string, System.ComponentModel.ListSortDirection> sorts, System.Collections.Generic.List<BookCatalog.Infrastructure.Filtration.CustomFilter> filters, int take, int skip) {
            this.sorts = sorts;
            this.filters = filters;
            this.take = take;
            this.skip = skip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooksResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel> GetBooksResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public GetBooksResponse() {
        }
        
        public GetBooksResponse(System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel> GetBooksResult, int total) {
            this.GetBooksResult = GetBooksResult;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXML", Namespace="http://tempuri.org/", Order=0)]
        public BookCatalog.Services.BookService.GetXMLRequestBody Body;
        
        public GetXMLRequest() {
        }
        
        public GetXMLRequest(BookCatalog.Services.BookService.GetXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetXMLRequestBody {
        
        public GetXMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public BookCatalog.Services.BookService.GetXMLResponseBody Body;
        
        public GetXMLResponse() {
        }
        
        public GetXMLResponse(BookCatalog.Services.BookService.GetXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetXMLResult;
        
        public GetXMLResponseBody() {
        }
        
        public GetXMLResponseBody(System.Xml.Linq.XElement GetXMLResult) {
            this.GetXMLResult = GetXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServiceChannel : BookCatalog.Services.BookService.IBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceClient : System.ServiceModel.ClientBase<BookCatalog.Services.BookService.IBookService>, BookCatalog.Services.BookService.IBookService {
        
        public BookServiceClient()
        {
            Infrastructure.Logging.Concrete.InfoLogger.Log("BookServiceClient", "Constructor");
        }
        
        public BookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
            Infrastructure.Logging.Concrete.InfoLogger.Log("BookServiceClient", "Constructor");
        }
        
        public BookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
            Infrastructure.Logging.Concrete.InfoLogger.Log("BookServiceClient", "Constructor");
        }
        
        public BookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
            Infrastructure.Logging.Concrete.InfoLogger.Log("BookServiceClient", "Constructor");
        }
        
        public BookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
            Infrastructure.Logging.Concrete.InfoLogger.Log("BookServiceClient", "Constructor");
        }

        ~BookServiceClient()
        {
            Infrastructure.Logging.Concrete.InfoLogger.Log("BookServiceClient", "Destructor");
        }

        public int GetBooksCount() {
            return base.Channel.GetBooksCount();
        }
        
        public System.Threading.Tasks.Task<int> GetBooksCountAsync() {
            return base.Channel.GetBooksCountAsync();
        }
        
        public System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel> GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel>> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCatalog.Services.BookService.GetBooksResponse BookCatalog.Services.BookService.IBookService.GetBooks(BookCatalog.Services.BookService.GetBooksRequest request) {
            return base.Channel.GetBooks(request);
        }
        
        public System.Collections.Generic.List<BookCatalog.Components.ViewModels.BookViewModel> GetBooks(System.Collections.Generic.Dictionary<string, System.ComponentModel.ListSortDirection> sorts, System.Collections.Generic.List<BookCatalog.Infrastructure.Filtration.CustomFilter> filters, int take, int skip, out int total) {
            BookCatalog.Services.BookService.GetBooksRequest inValue = new BookCatalog.Services.BookService.GetBooksRequest();
            inValue.sorts = sorts;
            inValue.filters = filters;
            inValue.take = take;
            inValue.skip = skip;
            BookCatalog.Services.BookService.GetBooksResponse retVal = ((BookCatalog.Services.BookService.IBookService)(this)).GetBooks(inValue);
            total = retVal.total;
            return retVal.GetBooksResult;
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Services.BookService.GetBooksResponse> GetBooksAsync(BookCatalog.Services.BookService.GetBooksRequest request) {
            return base.Channel.GetBooksAsync(request);
        }
        
        public bool BookExists(int id) {
            return base.Channel.BookExists(id);
        }
        
        public System.Threading.Tasks.Task<bool> BookExistsAsync(int id) {
            return base.Channel.BookExistsAsync(id);
        }
        
        public BookCatalog.Components.ViewModels.BookViewModel GetBook(int id) {
            return base.Channel.GetBook(id);
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Components.ViewModels.BookViewModel> GetBookAsync(int id) {
            return base.Channel.GetBookAsync(id);
        }
        
        public int Manage(BookCatalog.Components.ViewModels.BookViewModel bookVM) {
            return base.Channel.Manage(bookVM);
        }
        
        public System.Threading.Tasks.Task<int> ManageAsync(BookCatalog.Components.ViewModels.BookViewModel bookVM) {
            return base.Channel.ManageAsync(bookVM);
        }
        
        public void Delete(int bookId) {
            base.Channel.Delete(bookId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int bookId) {
            return base.Channel.DeleteAsync(bookId);
        }
        
        public string GetAuthors(int bookId) {
            return base.Channel.GetAuthors(bookId);
        }
        
        public System.Threading.Tasks.Task<string> GetAuthorsAsync(int bookId) {
            return base.Channel.GetAuthorsAsync(bookId);
        }
        
        public System.Collections.Generic.List<System.Web.Mvc.SelectListItem> PopulateMultiSelectList() {
            return base.Channel.PopulateMultiSelectList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Web.Mvc.SelectListItem>> PopulateMultiSelectListAsync() {
            return base.Channel.PopulateMultiSelectListAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCatalog.Services.BookService.GetXMLResponse BookCatalog.Services.BookService.IBookService.GetXML(BookCatalog.Services.BookService.GetXMLRequest request) {
            return base.Channel.GetXML(request);
        }
        
        public System.Xml.Linq.XElement GetXML() {
            BookCatalog.Services.BookService.GetXMLRequest inValue = new BookCatalog.Services.BookService.GetXMLRequest();
            inValue.Body = new BookCatalog.Services.BookService.GetXMLRequestBody();
            BookCatalog.Services.BookService.GetXMLResponse retVal = ((BookCatalog.Services.BookService.IBookService)(this)).GetXML(inValue);
            return retVal.Body.GetXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookCatalog.Services.BookService.GetXMLResponse> BookCatalog.Services.BookService.IBookService.GetXMLAsync(BookCatalog.Services.BookService.GetXMLRequest request) {
            return base.Channel.GetXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Services.BookService.GetXMLResponse> GetXMLAsync() {
            BookCatalog.Services.BookService.GetXMLRequest inValue = new BookCatalog.Services.BookService.GetXMLRequest();
            inValue.Body = new BookCatalog.Services.BookService.GetXMLRequestBody();
            return ((BookCatalog.Services.BookService.IBookService)(this)).GetXMLAsync(inValue);
        }
    }
}
