//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookCatalog.Services.AuthorWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bookcatalogwebservice.org/", ConfigurationName="AuthorWebService.AuthorWebServiceSoap")]
    public interface AuthorWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAllAuthors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        BookCatalog.Services.AuthorWebService.AuthorViewModel[] GetAllAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAllAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.AuthorViewModel[]> GetAllAuthorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAuthorsCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        int GetAuthorsCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAuthorsCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetAuthorsCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAuthors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        BookCatalog.Services.AuthorWebService.GetAuthorsResponse GetAuthors(BookCatalog.Services.AuthorWebService.GetAuthorsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.GetAuthorsResponse> GetAuthorsAsync(BookCatalog.Services.AuthorWebService.GetAuthorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetBooks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        string GetBooks(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetBooksAsync(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAuthor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        BookCatalog.Services.AuthorWebService.AuthorViewModel GetAuthor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.AuthorViewModel> GetAuthorAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/Manage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        int Manage(BookCatalog.Services.AuthorWebService.AuthorViewModel authorVM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/Manage", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ManageAsync(BookCatalog.Services.AuthorWebService.AuthorViewModel authorVM);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        void Delete(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int authorId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetTopAuthors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MemberInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CustomFilter[]))]
        BookCatalog.Services.AuthorWebService.TopAuthorViewModel[] GetTopAuthors(BookCatalog.Services.AuthorWebService.SearchTopAuthorsViewModel searchModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bookcatalogwebservice.org/GetTopAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.TopAuthorViewModel[]> GetTopAuthorsAsync(BookCatalog.Services.AuthorWebService.SearchTopAuthorsViewModel searchModel);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public partial class AuthorViewModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string firstNameField;
        
        private string secondNameField;
        
        private int booksCountField;
        
        private ShortBookViewModel[] booksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecondName {
            get {
                return this.secondNameField;
            }
            set {
                this.secondNameField = value;
                this.RaisePropertyChanged("SecondName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BooksCount {
            get {
                return this.booksCountField;
            }
            set {
                this.booksCountField = value;
                this.RaisePropertyChanged("BooksCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public ShortBookViewModel[] Books {
            get {
                return this.booksField;
            }
            set {
                this.booksField = value;
                this.RaisePropertyChanged("Books");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public partial class ShortBookViewModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int yearField;
        
        private int ratingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("Rating");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public partial class TopAuthorViewModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string firstNameField;
        
        private string secondNameField;
        
        private int totalRatingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecondName {
            get {
                return this.secondNameField;
            }
            set {
                this.secondNameField = value;
                this.RaisePropertyChanged("SecondName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int TotalRating {
            get {
                return this.totalRatingField;
            }
            set {
                this.totalRatingField = value;
                this.RaisePropertyChanged("TotalRating");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public partial class SearchTopAuthorsViewModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private System.DateTime beginDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime BeginDate {
            get {
                return this.beginDateField;
            }
            set {
                this.beginDateField = value;
                this.RaisePropertyChanged("BeginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("EndDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Type))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public abstract partial class MemberInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public abstract partial class Type : MemberInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public partial class CustomFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object valueField;
        
        private Type memberTypeField;
        
        private string memberField;
        
        private CustomOperator operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Type MemberType {
            get {
                return this.memberTypeField;
            }
            set {
                this.memberTypeField = value;
                this.RaisePropertyChanged("MemberType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
                this.RaisePropertyChanged("Member");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CustomOperator Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public enum CustomOperator {
        
        /// <remarks/>
        Contains,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        Less,
        
        /// <remarks/>
        GreaterOrEqual,
        
        /// <remarks/>
        LessOrEqual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public partial class Sort : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fieldNameField;
        
        private ListSortDirection sortDirectionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
                this.RaisePropertyChanged("FieldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ListSortDirection SortDirection {
            get {
                return this.sortDirectionField;
            }
            set {
                this.sortDirectionField = value;
                this.RaisePropertyChanged("SortDirection");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bookcatalogwebservice.org/")]
    public enum ListSortDirection {
        
        /// <remarks/>
        Ascending,
        
        /// <remarks/>
        Descending,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthors", WrapperNamespace="http://bookcatalogwebservice.org/", IsWrapped=true)]
    public partial class GetAuthorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bookcatalogwebservice.org/", Order=0)]
        public BookCatalog.Services.AuthorWebService.Sort[] sorts;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bookcatalogwebservice.org/", Order=1)]
        public BookCatalog.Services.AuthorWebService.CustomFilter[] filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bookcatalogwebservice.org/", Order=2)]
        public int take;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bookcatalogwebservice.org/", Order=3)]
        public int skip;
        
        public GetAuthorsRequest() {
        }
        
        public GetAuthorsRequest(BookCatalog.Services.AuthorWebService.Sort[] sorts, BookCatalog.Services.AuthorWebService.CustomFilter[] filters, int take, int skip) {
            this.sorts = sorts;
            this.filters = filters;
            this.take = take;
            this.skip = skip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthorsResponse", WrapperNamespace="http://bookcatalogwebservice.org/", IsWrapped=true)]
    public partial class GetAuthorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bookcatalogwebservice.org/", Order=0)]
        public BookCatalog.Services.AuthorWebService.AuthorViewModel[] GetAuthorsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bookcatalogwebservice.org/", Order=1)]
        public int total;
        
        public GetAuthorsResponse() {
        }
        
        public GetAuthorsResponse(BookCatalog.Services.AuthorWebService.AuthorViewModel[] GetAuthorsResult, int total) {
            this.GetAuthorsResult = GetAuthorsResult;
            this.total = total;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthorWebServiceSoapChannel : BookCatalog.Services.AuthorWebService.AuthorWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorWebServiceSoapClient : System.ServiceModel.ClientBase<BookCatalog.Services.AuthorWebService.AuthorWebServiceSoap>, BookCatalog.Services.AuthorWebService.AuthorWebServiceSoap {
        
        public AuthorWebServiceSoapClient() {
        }
        
        public AuthorWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookCatalog.Services.AuthorWebService.AuthorViewModel[] GetAllAuthors() {
            return base.Channel.GetAllAuthors();
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.AuthorViewModel[]> GetAllAuthorsAsync() {
            return base.Channel.GetAllAuthorsAsync();
        }
        
        public int GetAuthorsCount() {
            return base.Channel.GetAuthorsCount();
        }
        
        public System.Threading.Tasks.Task<int> GetAuthorsCountAsync() {
            return base.Channel.GetAuthorsCountAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookCatalog.Services.AuthorWebService.GetAuthorsResponse BookCatalog.Services.AuthorWebService.AuthorWebServiceSoap.GetAuthors(BookCatalog.Services.AuthorWebService.GetAuthorsRequest request) {
            return base.Channel.GetAuthors(request);
        }
        
        public BookCatalog.Services.AuthorWebService.AuthorViewModel[] GetAuthors(BookCatalog.Services.AuthorWebService.Sort[] sorts, BookCatalog.Services.AuthorWebService.CustomFilter[] filters, int take, int skip, out int total) {
            BookCatalog.Services.AuthorWebService.GetAuthorsRequest inValue = new BookCatalog.Services.AuthorWebService.GetAuthorsRequest();
            inValue.sorts = sorts;
            inValue.filters = filters;
            inValue.take = take;
            inValue.skip = skip;
            BookCatalog.Services.AuthorWebService.GetAuthorsResponse retVal = ((BookCatalog.Services.AuthorWebService.AuthorWebServiceSoap)(this)).GetAuthors(inValue);
            total = retVal.total;
            return retVal.GetAuthorsResult;
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.GetAuthorsResponse> GetAuthorsAsync(BookCatalog.Services.AuthorWebService.GetAuthorsRequest request) {
            return base.Channel.GetAuthorsAsync(request);
        }
        
        public string GetBooks(int authorId) {
            return base.Channel.GetBooks(authorId);
        }
        
        public System.Threading.Tasks.Task<string> GetBooksAsync(int authorId) {
            return base.Channel.GetBooksAsync(authorId);
        }
        
        public BookCatalog.Services.AuthorWebService.AuthorViewModel GetAuthor(int id) {
            return base.Channel.GetAuthor(id);
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.AuthorViewModel> GetAuthorAsync(int id) {
            return base.Channel.GetAuthorAsync(id);
        }
        
        public int Manage(BookCatalog.Services.AuthorWebService.AuthorViewModel authorVM) {
            return base.Channel.Manage(authorVM);
        }
        
        public System.Threading.Tasks.Task<int> ManageAsync(BookCatalog.Services.AuthorWebService.AuthorViewModel authorVM) {
            return base.Channel.ManageAsync(authorVM);
        }
        
        public void Delete(int authorId) {
            base.Channel.Delete(authorId);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int authorId) {
            return base.Channel.DeleteAsync(authorId);
        }
        
        public BookCatalog.Services.AuthorWebService.TopAuthorViewModel[] GetTopAuthors(BookCatalog.Services.AuthorWebService.SearchTopAuthorsViewModel searchModel) {
            return base.Channel.GetTopAuthors(searchModel);
        }
        
        public System.Threading.Tasks.Task<BookCatalog.Services.AuthorWebService.TopAuthorViewModel[]> GetTopAuthorsAsync(BookCatalog.Services.AuthorWebService.SearchTopAuthorsViewModel searchModel) {
            return base.Channel.GetTopAuthorsAsync(searchModel);
        }
    }
}
